idea_party/auth/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^', include('django.contrib.auth.urls')),
    
]

app_name = 'idea_party.auth'

idea_party/ideas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^new/$', views.idea_new, name="idea_new"),
    url(r'^idea/(?P<pk>[0-9]+)/$', views.idea_detail, name='idea_detail'),
    url(r'^idea/(?P<pk>[0-9]+)/edit/', views.idea_edit, name='idea_edit'),

]

idea_party/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views import static

import idea_party.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^$', idea_party.views.index, name='index'),
    url(r'^auth/', include('idea_party.auth.urls', namespace='auth')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^ideas/', include('idea_party.ideas.urls', namespace = 'ideas')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

idea_party/ideas/models.py
from django.conf import settings
from django.db import models


class Idea(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)

    def __str__(self):
        return self.title

    # def idea_belongs_to_user(request, self):
    #     return request.user == self.created_by

idea_party/ideas/forms.py
from django import forms

from .models import Idea


class IdeaForm(forms.ModelForm):
     class Meta:
        model = Idea
        fields = ('title', 'body',)

idea_party/ideas/views.py
from django.shortcuts import render, get_object_or_404
from .models import Idea
from .forms import IdeaForm
from django.shortcuts import redirect


def idea_new(request):
    if request.user.is_authenticated:
        user = request.user
        if request.method == "POST":
            form = IdeaForm(request.POST)
            if form.is_valid():
                idea = form.save(commit=False)
                idea.created_by = user
                idea.save()
                return redirect('ideas:idea_detail', pk=idea.pk)
        else:
            form = IdeaForm()
            return redirect('index')
    else:
        return redirect('index')


def idea_detail(request, pk):
    idea = get_object_or_404(Idea, pk=pk)
    return render(request, 'ideas/idea_detail.html', {'idea':idea})


def idea_edit(request, pk):
    idea = get_object_or_404(Idea, pk=pk)
    if request.user.is_authenticated and request.user==idea.created_by:
        if request.method == "POST":
            form = IdeaForm(request.POST, instance=idea)
            if form.is_valid():
                idea.save()
                return redirect('ideas:idea_detail', pk=idea.pk)
            else:
                form = IdeaForm(instance=idea)
        else:
            form = IdeaForm(instance=idea)
            return render(request, 'ideas/idea_edit.html', {'form': form})
    else:
        return redirect('ideas:idea_detail', pk=idea.pk)

idea_party/views.py
from django.shortcuts import render
from idea_party.ideas.models import Idea
from idea_party.ideas.forms import IdeaForm


def index(request):
    context = dict()
    context['form'] = IdeaForm()
    context['recent_ideas'] = Idea.objects.order_by('-created_on')[:5]
    return render(request, 'index.html', context)

idea_party/ideas/templates/ideas/idea_detail.html
{% extends 'base.html' %}

{% block full_title %}Idea Party{% endblock %}
{% block content %}
    <h2>{{ idea.title }}</h2>
    <p> {{ idea.body }}</p>
    {% if request.user.is_authenticated and request.user == idea.created_by %}
        <a href="{% url 'ideas:idea_edit' pk=idea.pk %} }">Edit this idea</a>
    {% endif %}

{% endblock %}

idea_party/ideas/templates/ideas/idea_edit.html
{% extends 'base.html' %}

{% block full_title %}Idea Party{% endblock %}


<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block content %}
    <h1>Make your changes</h1>
        <div class="form-group">
            <form method="POST" class="idea-form">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-default">Save</button>
            </form>
        </div>
    {% endblock %}
  </body>
</html>

idea_party/ideas/templates/ideas/idea_new.html
{% extends "base.html" %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block content %}
    <h1>What's your idea?</h1>
        <div class="form-group">
            <form method="POST" class="idea-form">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-default">Save</button>
            </form>
        </div>
    {% endblock %}
  </body>
</html>

idea_party/templates/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{% block full_title %}{% block title %}{% endblock %} - Bandwidth Portal{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/idea-party.css' %}">
    <link rel="icon" href="{% static 'lightbulb.png' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/lumen/bootstrap.min.css" rel="stylesheet" integrity="sha384-gv0oNvwnqzF6ULI9TVsSmnULNb3zasNysvWwfT/s4l8k5I+g6oFz9dye0wg3rQ2Q" crossorigin="anonymous">

    {% block extra_head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">💡 Idea Party</a>
        </div>
        <div class="collapse navbar-collapse" id="main-nav">
            <ul class="nav navbar-nav">
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="#">{{ user.username }}</a></li>
                    <li><a href="{% url 'auth:logout' %}">Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'auth:login' %}">Log In</a></li>
                    <li><a href="{% url 'auth:register' %}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}


</div>
<footer></footer>
<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="{% static 'scripts.js' %}"></script>
{% block extra_body %}{% endblock %}
</body>
</html>

idea_party/templates/index.html
{% extends 'base.html' %}

{% block full_title %}Idea Party{% endblock %}

{% block content %}
    <p>Hello, World!</p>
    {% if user.is_authenticated %}
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Feeling Inspired? Add Your Idea!</button>
    {% endif %}

    {% for idea in recent_ideas %}
        <div class="idea-tile">
            <h2><a href="{% url 'ideas:idea_detail' pk=idea.pk %}">{{ idea.title }}</a></h2>
        </div>
    {% endfor %}

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Add your idea</h4>
          </div>
          <div class="modal-body">
              <h1>What's your idea?</h1>
            <div class="form-group">
                <form method="POST" action="{% url 'ideas:idea_new' %}"class="idea-form">{% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-default">Save</button>

                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}